# Set master image
FROM php:7.4-fpm-alpine

# Set working directory
WORKDIR /var/www/html

# Install PHP Composer
#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Remove Cache
RUN rm -rf /var/cache/apk/*


# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
